### ISSUE TITLE
Change license to a more permissive one.

### ISSUE THREAD

**Issue by pires** [BITalinoWorld/revolution-android-api#1]
By licensing this as GPL, you force every adopter to release their code as GPL.

**Comment by alemos-plux** [comment]
Hi @pires. That is exactly right. We're currently operating on a dual license model so that the community can assist us in evolving the code. 

If the code needs to remain proprietary, a different license is available. We will be adding this information to the code shortly.

**Comment by hypergalaxy** [comment]
Where can we find info on this different license?

**Comment by a-fazal** [comment]
What is the other license? Don't see it in the code

**Comment by GTelo** [comment]
The license was updated for Apache-2.0. 

Thanks for your preference for BITalino devices and for your feedback
