### ISSUE TITLE
setFreq in BTHCommunication

### ISSUE THREAD

**Issue by ThunderAnimal** [BITalinoWorld/revolution-android-api#2]
wouldn't it make sense to use the sampleRate given to the method?
-> https://github.com/BITalinoWorld/revolution-android-api/blob/master/api/src/main/java/info/plux/pluxapi/bitalino/bth/BTHCommunication.java#L207

```
    @Override
    protected boolean setFreq(int sampleRate) throws BITalinoException {
        CommandArguments commandArguments = new CommandArguments();
        commandArguments.setSampleRate(validateSampleRate(sampleRate));

        byte[] command = BITalino.SET_FREQ.getCommand(commandArguments).command;

        try {
            mConnectedThread.write(command);
        } catch (Exception e) {
            throw new BITalinoException(BITalinoErrorTypes.BT_DEVICE_NOT_CONNECTED);
        }
        return true;
    }
```

**Comment by GTelo** [comment]
Hi @ThunderAnimal. You are totally right, I introduced that hard coded 1000 Hz when I was doing the API debug.  A commit was missing in the history.

I will push the missing commit. Thank you very much for your input.
