### ISSUE TITLE
BITalino connection using BLE  doesn't start although device is correctly discovered

### ISSUE THREAD

**Issue by bestmazzo** [BITalinoWorld/revolution-android-api#5]
When tapping the CONNECT button status changes to CONNECTING and remains so.
Trying to debug, I noticed the connect procedure throws a error (see log below).
Any idea how to solve this?

05-09 18:16:48.795 30395-30395/info.plux.pluxapi.sampleapp W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/info.plux.pluxapi.sampleapp-2/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@info.plux.pluxapi.sampleapp-2@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
05-09 18:16:48.799 30395-30395/info.plux.pluxapi.sampleapp W/System: ClassLoader referenced unknown path: /data/app/info.plux.pluxapi.sampleapp-2/lib/arm
05-09 18:16:48.804 30395-30395/info.plux.pluxapi.sampleapp I/InstantRun: starting instant run server: is main process
05-09 18:16:53.730 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x0104041c, entry index(1052) is beyond type entryCount(1)
05-09 18:16:53.788 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b2, entry index(1202) is beyond type entryCount(1)
05-09 18:16:53.793 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b1, entry index(1201) is beyond type entryCount(1)
05-09 18:16:53.798 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b1, entry index(1201) is beyond type entryCount(1)
05-09 18:16:53.798 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b4, entry index(1204) is beyond type entryCount(1)
05-09 18:16:53.829 30395-30696/info.plux.pluxapi.sampleapp D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
05-09 18:16:53.852 30395-30395/info.plux.pluxapi.sampleapp D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@4978533
05-09 18:16:53.874 30395-30696/info.plux.pluxapi.sampleapp I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.6_RB1__release_AU (Idd51518bdf)
                                                                         OpenGL ES Shader Compiler Version: XE031.06.00.02
                                                                         Build Date: 12/11/15 Fri
                                                                         Local Branch: 
                                                                         Remote Branch: quic/LA.BR.1.2.6_rb1.5
                                                                         Local Patches: NONE
                                                                         Reconstruct Branch: NOTHING
05-09 18:16:53.880 30395-30696/info.plux.pluxapi.sampleapp I/OpenGLRenderer: Initialized EGL, version 1.4
05-09 18:16:53.906 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b3, entry index(1203) is beyond type entryCount(1)
05-09 18:16:53.908 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x01040345, entry index(837) is beyond type entryCount(1)
05-09 18:16:53.908 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x01040347, entry index(839) is beyond type entryCount(1)
05-09 18:16:53.909 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x01040348, entry index(840) is beyond type entryCount(1)
05-09 18:16:53.909 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x01040346, entry index(838) is beyond type entryCount(1)
05-09 18:16:53.951 30395-30395/info.plux.pluxapi.sampleapp D/BTHDeviceScan: device found: Hugs VIP - 6B:DA:A3:55:54:DE
05-09 18:16:53.955 30395-30395/info.plux.pluxapi.sampleapp D/BTHDeviceScan: device found: Hugs VIP - 6B:DA:A3:55:54:DE
05-09 18:16:53.963 30395-30395/info.plux.pluxapi.sampleapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@4974cf9 time:2956441
05-09 18:16:55.232 30395-30395/info.plux.pluxapi.sampleapp D/BTHDeviceScan: device found: BITalino BLE - 24:71:89:45:C1:E7
05-09 18:17:00.815 30395-30395/info.plux.pluxapi.sampleapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
05-09 18:17:00.882 30395-30395/info.plux.pluxapi.sampleapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
05-09 18:17:00.951 30395-30395/info.plux.pluxapi.sampleapp I/AudioManagerEx: AudioManagerEx created
05-09 18:17:00.965 30395-30395/info.plux.pluxapi.sampleapp I/Timeline: Timeline: Activity_launch_request id:info.plux.pluxapi.sampleapp time:2963443
05-09 18:17:01.044 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x0104041c, entry index(1052) is beyond type entryCount(1)
05-09 18:17:01.049 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b2, entry index(1202) is beyond type entryCount(1)
05-09 18:17:01.052 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b1, entry index(1201) is beyond type entryCount(1)
05-09 18:17:01.054 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b1, entry index(1201) is beyond type entryCount(1)
05-09 18:17:01.075 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x0104041c, entry index(1052) is beyond type entryCount(1)
05-09 18:17:01.078 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x0104041c, entry index(1052) is beyond type entryCount(1)
05-09 18:17:01.085 30395-30395/info.plux.pluxapi.sampleapp D/DeviceActivity: Communication: BLE
05-09 18:17:01.112 30395-30395/info.plux.pluxapi.sampleapp D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@4b0f97b
05-09 18:17:01.143 30395-30395/info.plux.pluxapi.sampleapp W/ResourceType: For resource 0x010404b3, entry index(1203) is beyond type entryCount(1)
05-09 18:17:01.173 30395-30395/info.plux.pluxapi.sampleapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@b4da975 time:2963650
05-09 18:17:03.765 30395-30395/info.plux.pluxapi.sampleapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
05-09 18:17:04.130 30395-30395/info.plux.pluxapi.sampleapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
05-09 18:17:04.131 30395-30395/info.plux.pluxapi.sampleapp I/AudioManagerEx: AudioManagerEx created
05-09 18:17:04.134 30395-30395/info.plux.pluxapi.sampleapp D/BluetoothGatt: connect() - device: 24:71:89:45:C1:E7, auto: true
05-09 18:17:04.135 30395-30395/info.plux.pluxapi.sampleapp D/BluetoothGatt: registerApp()
05-09 18:17:04.139 30395-30395/info.plux.pluxapi.sampleapp D/BluetoothGatt: registerApp() - UUID=04842bd1-c6ec-48af-8bc4-3ecc1d95bbd4
05-09 18:17:04.142 30395-30408/info.plux.pluxapi.sampleapp D/BluetoothGatt: onClientRegistered() - status=0 clientIf=6
05-09 18:17:04.143 30395-30395/info.plux.pluxapi.sampleapp D/BLECommunication: 24:71:89:45:C1:E7 - Trying to create a new connection.
05-09 18:17:04.146 30395-30395/info.plux.pluxapi.sampleapp I/DeviceActivity: 24:71:89:45:C1:E7 -> CONNECTING
05-09 18:17:04.536 30395-30406/info.plux.pluxapi.sampleapp D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=6 device=24:71:89:45:C1:E7
05-09 18:17:04.536 30395-30406/info.plux.pluxapi.sampleapp I/BLECommunication: 24:71:89:45:C1:E7 - Connected to GATT server.
05-09 18:17:04.537 30395-30406/info.plux.pluxapi.sampleapp D/BluetoothGatt: discoverServices() - device: 24:71:89:45:C1:E7
05-09 18:17:04.541 30395-30406/info.plux.pluxapi.sampleapp I/BLECommunication: 24:71:89:45:C1:E7 - Attempting to start service discovery:true
05-09 18:17:04.569 30395-30406/info.plux.pluxapi.sampleapp D/BluetoothGatt: onSearchComplete() = Device=24:71:89:45:C1:E7 Status=0
05-09 18:17:06.569 30395-30395/info.plux.pluxapi.sampleapp D/BLECommunication: reconnect()
05-09 18:17:06.573 30395-30395/info.plux.pluxapi.sampleapp W/System.err: info.plux.pluxapi.bitalino.BITalinoException: Bluetooth Device not connected
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication.disconnect(BLECommunication.java:697)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication.reconnect(BLECommunication.java:1005)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication.access$900(BLECommunication.java:35)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication$2.onReceive(BLECommunication.java:271)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:925)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5551)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
05-09 18:17:06.574 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
05-09 18:17:06.824 30395-30395/info.plux.pluxapi.sampleapp W/System.err: info.plux.pluxapi.bitalino.BITalinoException: Device not in idle mode
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication.connect(BLECommunication.java:672)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication.reconnect(BLECommunication.java:1017)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication.access$900(BLECommunication.java:35)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at info.plux.pluxapi.bitalino.ble.BLECommunication$2.onReceive(BLECommunication.java:271)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:925)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5551)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
05-09 18:17:06.825 30395-30395/info.plux.pluxapi.sampleapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by GTelo** [comment]
Hi @bestmazzo,

This is indeed a odd issue, I have been trying to reproduce your problem but with no success. Do you have your local project updated?

Looking to your logcat, you are having a problem when the API tries to search the device's services. This task is failing the callback which answer is never triggered, this normally occurs with some mobile devices that don't have the BLE features fully implemented. Have you tried with different mobile devices?

You can also try to disable/enable the mobile device's bluetooth adapter, to make sure that its bluetooth is not in a strange mode.

Gonçalo Telo
