### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Melchester** [BITalinoWorld/revolution-android-api#7]
Hello, so sorry to miss-use this option, there is no issue except that I could not find anyway to contact you. Is there any documentation for this software? To be honest I cannot even work out how to use the sample app. I can connect and receive data, but what are the PWM and Battery Threshold buttons and sliders for?

**Comment by GTelo** [comment]
Hi @Melchester,

you can find the documentation here: http://bitalino.com/docs/android-api.pdf.

The PWM slider allows you to set the value to be assigned as the analog (PWM) value to your BITalino.

And the Battery slider allows you to select a new battery threshold for the low-battery LED.

Best regards,
Gonçalo Telo

**Comment by Melchester** [comment]
Super.  Thanks very much.
