### ISSUE TITLE
BLE loses packets at 1000 Hz

### ISSUE THREAD

**Issue by syed-ahmed** [BITalinoWorld/revolution-android-api#8]
Hi,

I wasn't able to get meaningful data from BLE at 1000 Hz due to packet loss as seen in the attached figure. However, I was able to get correct number of sequences at 10 Hz (but resolution is too low at 10Hz to see meaningful data). 

![image](https://user-images.githubusercontent.com/8906225/39258352-d1fe64e4-4881-11e8-9ad3-59dea9d63635.png)

**Comment by ThunderAnimal** [comment]
we had the same problem, when we playing a little bit around with that during an uni project. Our solution was to just ignore these `invalid` data. So we wrote a computation  wich seperate the `good` data from the `bad` data, an then make an average about the good data in a specific time frame.

I don't know if that the right approche but it seem for us the only one possible solution

**Comment by syed-ahmed** [comment]
Interesting. We were doing this for a uni project as well. We ended up using the normal bluetooth. That works fine with the 1000 Hz.

**Comment by GTelo** [comment]
Hi @syed-ahmed 

The BLE has some limitations concerning the data streaming capability. Also, the behaviour of the Bluetooth changes between devices and manufacturers.

You should be able to acquire all BITalino's channels at a sampling rate of 100 Hz. However if you choose to use 1000 Hz, you will lose frames. To stream data at this rate we recommend the use of the classical Bluetooth.

Anything else that you may need please let me know.
